### ISSUE TITLE
Error after upgrade to 1.5.0

### ISSUE THREAD

**Issue by kogal** [mobilusoss/react-notification-badge#38]
After upgrading to 1.5.0 I get this error:

> Cannot find module 'core-js/modules/es.object.define-property'

**Comment by georgeOsdDev** [comment]
It works without any extra dependencies.
https://codesandbox.io/s/hardcore-leaf-ss3d5?fontsize=14

I found some issues which references
> Cannot find module 'core-js/modules/es.object.define-property'
- https://github.com/babel/babel/issues/9734#issue-423654875
- https://github.com/zeit/next.js/issues/6332

Please try to add core-js to your app dependencies.
